### PR TITLE
feat(): update scraper to return Promise

### PR DESCRIPTION
**Pull request by coogie**
_Additional Fixes_
- Restore `release_date` by way of regex on page's `h1` tag

_Additional Changes_
- Update some variables to use ES6 `const`
- Update `issue` object literal to make use of ES6 shorthand assignments
- Reduce code used to assign `price` to `issue` object

### CODE REVIEW

**Comment by coogie** [comment]
Hihi

Hope you don't mind, but I stumbled across this module a short while back and I've been slowly implementing into a project of my own.

I've made some changes to it that suited me (notably Promise and a fix for `release_date`), and feel I should contribute back. :D
There are some minor ES6 changes (const) that can be dropped if you don't want them.

My target environment is Node 5

**Comment by dmamills** [comment]
Hey! Thanks for these changes, glad you found some usefulness out this project :+1:

**Comment by dmamills** [comment]
I published it to npm under version 1.0, I just made one small change in that it requiring it returns a function that returns a promise `comiclist().then(fn)` instead of `comiclist.then(fn)`

**Comment by coogie** [comment]
Thanks for the heads up, I'll update my deps.
And cool, that actually makes more sense when you think about it... :p

**Pull request merged**
